# Site settings
title: CloudMagician
description: "A blog about CloudMagician ..."
baseurl: ""
url: "http://CloudMagician.github.io/"

# User settings
username: CloudMagician
user_title: CloudMagician
email: luzx1916@mails.jlu.edu.cn
twitter_username: CloudMagician94
github_username:  CloudMagician
# gplus_username:  CloudMagician
# linkedin_public_url: CloudMagician
# disqus_username: CloudMagician
profile_picture: /assets/img/profile_picture.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/CloudMagician
      new_tab: true
      key_trigger: g
    - title: twitter
      url: https://twitter.com/CloudMagician94
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: JLU Life
    url: https://github.com/Steven128/JLUlife

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
